CREATE OR REPLACE PACKAGE OPS$ANDES.PKG_PCA_RENTINFORMADAS_OBTENER AS 

  /* TODO enter package declarations (types, exceptions, methods etc) here */ 
  TYPE V_CURSOR IS REF CURSOR;
 SUBTYPE ST_TIPO_VARCHAR2_10 IS VARCHAR2(10 CHAR);
 SUBTYPE ST_TIPO_VARCHAR2_50 IS VARCHAR2(50 CHAR);
 SUBTYPE ST_TIPO_NUMBER IS NUMBER(5);
 SUBTYPE ST_TIPO_NUMBER_9 IS NUMBER(9); 
 PROCEDURE PRC_OBTENER_PCA_RENTINFORMADAS (P_PER_RUT IN afi_persona.per_rut%type,
                                       V_RENTINFORMADAS    OUT V_CURSOR); 

END PKG_PCA_RENTINFORMADAS_OBTENER;